version: "3"
services:
  server:
    container_name: "onicha"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - my-network

  database:
    image: mongo:latest
    container_name: "database"
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=onicha
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=password
    networks:
      - my-network

networks:
  my-network:
    driver: bridge